interface app {
use standard.{address};

    // Function signature for: get-messages (http)
    // HTTP: POST /api/get-messages
    record get-messages-signature-http {
        target: string,
        request-body: string,
        returning: string
    }

    // Function signature for: get-status (http)
    // HTTP: POST /api/get-status
    record get-status-signature-http {
        target: string,
        request-body: string,
        returning: string
    }

    // Function signature for: increment-counter (http)
    // HTTP: POST /api/increment-counter
    record increment-counter-signature-http {
        target: string,
        request-body: string,
        returning: result<u32, string>
    }
}
